defaults:
  - _aces
  - override data: sharded
  - _self_

dataset_name: ${oc.env:MEDS_DATASET_NAME}
task_name: ${oc.env:MEDS_TASK_NAME}
output_dir: "${oc.env:MEDS_ROOT_DIR}/task_labels"

# TODO: find a nice way to have this be inferred automatically
MEDS_DEV_dir: "${oc.env:MEDS_DEV_REPO_DIR}"

data:
  standard: meds
  root: "${oc.env:MEDS_ROOT_DIR}/data"

# Cohort directory and name: used for automatically loading configs, saving results, and logging.
cohort_dir: ${output_dir}
cohort_name: ${task_name}

# Path to the task configuration file
config_path: ${MEDS_DEV_dir}/tasks/criteria/${task_name}.yaml
predicates_path: ${MEDS_DEV_dir}/datasets/${dataset_name}/predicates.yaml
