description: >-
  This file specifies the base configuration for the extraction and analysis of sepsis prediction in patients
  admitted to the hospital. The study uses the sepsis 3 definition of an acute increase in SOFA of 2 points (24hrs). 
  https://jamanetwork.com/journals/jama/fullarticle/2492881.
  https://pubmed.ncbi.nlm.nih.gov/27694098/

predicates:
  hospital_admission:
    code: event_type//HOSPITAL_ADMISSION
  hospital_discharge:
    code: event_type//HOSPITAL_DISCHARGE
  death:
    code: event_type//DEATH
  age:
    code: demographics//AGE
    value_min: 18
    value_min_inclusive: true
  sofa_initial:
    code: score//SOFA
    time: trigger
  sofa_24h:
    code: score//SOFA
    time: trigger + 24h
  sofa_increase:
    expr: sofa_24h - sofa_initial >= 2
  esi_threshold_met:
    code: esi_score
    value_min: 6
    value_min_inclusive: true
  sepsis:
    expr: sofa_increase

trigger: hospital_admission

windows:
  input:
    start: NULL
    end: trigger + 24h
    start_inclusive: true
    end_inclusive: true
    has:
      age: (18, None)
      esi_threshold_met: (None, None)
  gap:
    start: input.end
    end: trigger + 24h
    start_inclusive: false
    end_inclusive: true
    has:
      sepsis: (None, 0)
  target:
    start: gap.end
    end: hospital_discharge
    start_inclusive: false
    end_inclusive: true
    label: sepsis
