description: >-
  This task predicts whether a patient's hospital admission will be LESS than three days using only the data
  from the first 24 hours of their admission to the hospital. Only patient's whose hospital stay is at least
  48 hours will be included to avoid future leakage and the edge case of predicting immediate discharge or
  death as a proxy for a shorter length of stay. Note that patients who die in the admission of interest are
  still included in this task, so a prediction of a short length of stay should **not** be considered a proxy
  for good health, as the model may be predicting a risk of early mortality rather than early discharge.
  Note that, due to limitations of the ACES tool and the predicates it can extract, here we are really
  predicting _short_ length of stay, not _long_ length of stay.

predicates:
  hospital_admission:
    code: ???
  hospital_discharge:
    code: ???
  death:
    code: ???
  discharge_or_death:
    expr: or(hospital_discharge, death)

trigger: hospital_admission

windows:
  input:
    start: NULL
    end: trigger + 24h
    start_inclusive: True
    end_inclusive: True
  gap:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      hospital_admission: (None, 0)
      discharge_or_death: (None, 0)
  target:
    start: trigger
    end: start + 3d
    start_inclusive: False
    end_inclusive: True
    label: discharge_or_death
