description: >- This file specifies the base configuration for the prediction of within 2-year unspecified
  mortality. Given the other tasks in this directory, we impose a 30-day gap window here, so that this task
  can be used alongside that task to form a complete picture of the patient state and so that this task can
  focus on larger windows of time rather than more imminent risks. Note that there is no censoring protection
  for this task -- e.g., if the patient has no data after 2 years from the trigger event, they will be assumed
  to have survived. They must, however, have data after the gap window, so there is censoring protection from
  that point of view.
  Note that this task is an unspecified mortality prediction, unconditioned on the trigger event, not in-hospital,
  in-ICU, or post-discharge mortality.
  This task will have a very large number of negative examples, and a very small number of positive examples.

predicates:
  death:
    code: ???

trigger: _ANY_EVENT

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    has:
      death: (null, 0) # death must not have occurred before the trigger event
  gap:
    start: input.end
    end: input.end + 30d
    start_inclusive: True
    end_inclusive: True
    has:
      death: (0, null) # death must not have occurred after the gap window
  target:
    start: gap.end
    end: start + 700d # 2 years in total
    start_inclusive: False
    end_inclusive: True
    label: death
    has:
      _ANY_EVENT: (1, null) # must have at least one event in the target window
