description: >-
  This file specifies the base configuration for the extraction and analysis of acute respiratory distress syndrome (ARDS)
  in patients admitted to the ICU. ARDS is defined based on the Berlin definition and requires specific clinical measurements and radiology reports that should be calculated post-hoc.
  https://pdf.sciencedirectassets.com/272986/1-s2.0-S0883944120X00050/1-s2.0-S0883944120306237/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjECEaCXVzLWVhc3QtMSJHMEUCIQDp98qVWjgHT%2F%2BLW8G216FvEi1cJjlKi7LHB%2BYpl8GPYwIgVMS6JE0MkEqHDQaCk2IHoZh7b7ZIuaBJFTLBYllHQSoqvAUIqf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARAFGgwwNTkwMDM1NDY4NjUiDKAjF6nOPNLq68bATiqQBQHbnIqoB2ciW4vXYJ8J3WtQVnUZ0U%2F5GUjNIPyVQnlY3KZXRfpb%2FvtvJY8ErwJNxoSQm3h%2FR3%2BQHaY3iEGZk7d698ADwge6RMP%2Fwoa5KaaGbUcnwvRgNejdM4fczlNDEvPe9AxIFITNcWC%2FN95y4P5cu9edDEbHexJchTzvVEKf7K%2Frxd46XZr1q8VovFVwozejcV3t4oLkvMARfrQEf%2FZr9b2yCtuIV42Gg09ISuwldUPkynOCTnX46IQYiFIC%2BwDX%2FAaKVUaJouQqtjPCETpHs86WJzDUWLea4q6rarbTG8U11ruB02i9HFujqQceREE53AVeOW0OPqMTEynPOjNQ7Sh2aOcNC5bqxHNZTb9XPIiAr4d0heyP%2FSsJaWssRagp%2FLaNH%2FRL1DgB%2FqCX9lrwHRluJFTPo135SI9pVpsLIIME5SwyGv4EcRthDFI8GktbKYRLoYivaqEmY7DtkRUbi0NFn2ejEknGTTJb%2FrXr2binzrzY2IozeTHvKpe31fVHxZcISpyPiOaS36u2npSwu6EIZsHPDzbhpR8AQnVVH6wLdrPdMPHKGHUtz%2BNTTOz9tjFneTwj8x6FXd8Gs7Ga1rgiz18BZgngHOW1RC2%2Ff80aVsWmkxYCTEbOueq282GaBoprISLJmZezK0nsIlpWMlVgLkHt8ZZC51CbfflOkK7NPM6pWrXMzskrbm%2FltSfAikL1irWF2sBHe5mK8Obu6PlYIb%2BZk%2FTKkjaYtwIcDPFRRLD5o0z1KXZvYJ9pampZMNrfuctEsFHC6Psa9xCfaZpBWjy1k2BN52%2BhtAf0gRCbMwEv7cx6mlMcpagTKmyeBeuKQfebLu3K0hwmEOpNGQ8y2%2B6kqlcSpsYkw7MXML%2F8%2FLIGOrEBtqgdtSo8%2FimUr2%2FF8xRhQis7wtiQlH1LFTsjevBho%2B81b8sgE51LGC9oJRbwDPtv%2BI13JvlISqdDmccM4ojdizmHlDgEK5KlEQH1XJnm9%2Ff7T%2B6IwptnsAWg1hGZk%2BYYOVRre1P7lUZ3ED05ug4ThoXQPoZC%2FGpmX1NMfxIhULcgYvHg68QypeAP9gGl7Xhol%2FzXPmuYv3I4Uhp8hLQgHIOay492TQF8S1%2Fmuxh%2BrghT&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20240604T180417Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTYTOF5YT27%2F20240604%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=7f5ca435d8765062ae509ea9acb24ad41165c8a6d4758fb8a0c33156cf45a673&hash=18f10dc84abdc27326d034c6e89294c6c32248d8586f7b1f211b3d5cd8784322&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0883944120306237&tid=spdf-c598764c-d4e9-4c67-ba9f-b9e7d206ec02&sid=5f711abe340656428809edf0b0a69334f70dgxrqa&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=1311565601590358515f&rr=88e9d8313ccb4cd2&cc=us
  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7417145/pdf/cc9-2-e0175.pdf

predicates:
  icu_admission:
    code: event_type//ICU_ADMISSION
  icu_discharge:
    code: event_type//ICU_DISCHARGE
  death:
    code: event_type//DEATH
  age:
    code: demographics//AGE
    value_min: 18
    value_min_inclusive: true
  mechanical_ventilation:
    code: treatment//MECHANICAL_VENTILATION
  cxr_present:
    code: radiology//CXR
  peep:
    code: ventilation//PEEP
    value_min: 5
    value_min_inclusive: true
  p_f_ratio:
    code: lab//P_F_RATIO
    value_max: 300
    value_max_inclusive: true
  bilateral_opacities:
    code: radiology//BILATERAL_OPACITIES
  infiltrates:
    code: radiology//INFILTRATES
  tracheostomy:
    code: procedure//TRACHEOSTOMY
  ards:
    expr: and(peep, p_f_ratio, or(bilateral_opacities, infiltrates))

trigger: icu_admission

windows:
  input:
    start: NULL
    end: trigger + 24h
    start_inclusive: true
    end_inclusive: true
    has:
      age: (18, None)
      cxr_present: (1, None)
      mechanical_ventilation: (None, None)
      peep: (None, None)
      p_f_ratio: (None, None)
      bilateral_opacities: (None, None)
      infiltrates: (None, None)
  gap:
    start: input.end
    end: trigger + 72h
    start_inclusive: false
    end_inclusive: true
    has:
      tracheostomy: (None, 0)
  target:
    start: gap.end
    end: icu_discharge
    start_inclusive: false
    end_inclusive: true
    label: ards