description: >-
  This file specifies the base configuration for the extraction and analysis of antibiotic dosing in patients 
  admitted to the ICU, leveraging data from the MIMIC-IV database. The study focuses on adult patients and aims 
  to personalize antibiotic dosing based on patient characteristics and pharmacokinetic (PK) models.
  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10353957/

predicates:
  icu_admission:
    code: event_type//ICU_ADMISSION
  icu_discharge:
    code: event_type//ICU_DISCHARGE
  age:
    code: demographics//AGE
    value_min: 18
    value_min_inclusive: true
  antibiotic_admin:
    code: treatment//ANTIBIOTIC_ADMIN
  ciprofloxacin_admin:
    code: treatment//CIPROFLOXACIN_ADMIN
  beta_lactam_admin:
    code: treatment//BETA_LACTAM_ADMIN
  serum_creatinine:
    code: lab//SERUM_CREATININE
  gfr:
    code: lab//GFR
  antibiotic_concentration:
    code: lab//ANTIBIOTIC_CONCENTRATION
  renal_function:
    expr: or(serum_creatinine, gfr)

trigger: icu_admission

windows:
  input:
    start: NULL
    end: trigger + 24h
    start_inclusive: true
    end_inclusive: true
    has:
      age: (18, None)
      antibiotic_admin: (None, None)
      serum_creatinine: (None, None)
      gfr: (None, None)
  gap:
    start: input.end
    end: trigger + 6h
    start_inclusive: false
    end_inclusive: true
    has:
      antibiotic_admin: (None, None)
  target:
    start: gap.end
    end: icu_discharge
    start_inclusive: false
    end_inclusive: true
    label: antibiotic_concentration

# cohort:
#   inclusion_criteria:
#     - age >= 18
#     - icu_admission
#     - antibiotic_admin
#   exclusion_criteria:
#     - missing or erroneous values
#   data_extracted:
#     - age
#     - gender
#     - ethnicity
#     - antibiotic_admin
#     - ciprofloxacin_admin
#     - beta_lactam_admin
#     - serum_creatinine
#     - gfr
#     - vital_signs
#     - lab_values
#     - clinical_notes
#     - antibiotic_concentration

# antibiotic_dosing_definition:
#   criteria:
#     - condition: administration of ciprofloxacin or beta-lactam antibiotics
#     - condition: monitoring of serum creatinine or GFR for renal function
#   exclusion: missing or erroneous values
