description: >-
  This file specifies the base configuration for the extraction and analysis of acute kidney injury (AKI)
  in patients admitted to the ICU, leveraging data from the first 24 hours of ICU admission and subsequent
  days for determining AKI status. The study focuses on adult patients with no pre-existing Chronic Kidney
  Disease (CKD), using data from the Medical Information Mart for Intensive Care III (MIMIC-III) database. 
  Based on https://ebooks.iospress.nl/publication/52010.

predicates:
  icu_admission:
    code: event_type//ICU_ADMISSION
  icu_discharge:
    code: event_type//ICU_DISCHARGE
  death:
    code: event_type//DEATH
  ckd:
    code: diagnosis//CHRONIC_KIDNEY_DISEASE
  age:
    code: demographics//AGE
    value_min: 18
    value_min_inclusive: true
  gfr:
    code: lab//GFR
    value_min: 60
    value_min_inclusive: true
  creatinine_day1:
    code: lab//SERUM_CREATININE
    time: trigger + 24h
  creatinine_day2:
    code: lab//SERUM_CREATININE
    time: trigger + 48h
  creatinine_day3:
    code: lab//SERUM_CREATININE
    time: trigger + 72h
  aki_on_admission:
    expr: or(creatinine_day1_increase, creatinine_day1_change)
  creatinine_day1_increase:
    expr: creatinine_day1 - creatinine_baseline >= 0.3
  creatinine_day1_change:
    expr: creatinine_day1 / creatinine_baseline >= 1.5
  aki:
    expr: or(creatinine_day2_increase, creatinine_day2_change, creatinine_day3_increase, creatinine_day3_change)
  creatinine_day2_increase:
    expr: creatinine_day2 - creatinine_day1 >= 0.3
  creatinine_day2_change:
    expr: creatinine_day2 / creatinine_day1 >= 1.5
  creatinine_day3_increase:
    expr: creatinine_day3 - creatinine_day1 >= 0.3
  creatinine_day3_change:
    expr: creatinine_day3 / creatinine_day1 >= 1.5

trigger: icu_admission

windows:
  input:
    start: NULL
    end: trigger + 24h
    start_inclusive: true
    end_inclusive: true
    has:
      age: (18, None)
      gfr: (60, None)
      creatinine_day1: (None, None)
      vitals_day1: (None, None)
      lab_values_day1: (None, None)
      mechanical_ventilation_day1: (None, None)
      urine_output_day1: (None, None)
      clinical_notes_day1: (None, None)
  gap:
    start: input.end
    end: start + 48h
    start_inclusive: false
    end_inclusive: true
    has:
      creatinine_day2: (None, None)
      creatinine_day3: (None, None)
  target:
    start: gap.end
    end: icu_discharge
    start_inclusive: false
    end_inclusive: true
    label: aki
