defaults:
  - _self_
  - override hydra/hydra_logging: disabled

dataset_dir: ???
labels_dir: ???
output_dir: ???
predictions_fp: ${output_dir}/predictions.parquet
split: "held_out"
seed: 1
num_threads: 4

hydra:
  run:
    dir: ${output_dir}
