description: >-
  This task predicts whether the patient will have abnormal _platelets_ values within the next 24
  hours, given the first 24 hours of their admission to the ICU. To be included, patients must have
  at least one measurement for _platelets_ within the next 24 hours after their admission to ICU,
  and their length of stay in ICU should be at least 24 hours.

predicates:
  icu_admission: ???
  icu_discharge: ???
  hospital_discharge: ???
  death: ???
  discharge_or_death:
    expr: or(icu_discharge, death, hospital_discharge)

  # Plain predicates
  platelets:
    code: ???
  abnormal_platelets:
    code: ???
    value_min: null
    value_max: ???

trigger: icu_admission

windows:
  input:
    start: null
    end: trigger + 24h
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
    has:
      # do not allow icu discharge to happen in the input window
      icu_admission: (None, 1)
      discharge_or_death: (None, 0)
  target:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      platelets: (1, None)
    label: abnormal_platelets