description: >-
  This task predicts whether the patient will have low _sodium_ values within the next 24
  hours, given the first 24 hours of their admission to the ICU. To be included, patients must have
  at least one measurement for _sodium_ within the next 24 hours after their admission to ICU,
  and their length of stay in ICU should be at least 24 hours.

predicates:
  icu_admission: ???
  icu_discharge: ???
  hospital_discharge: ???
  death: ???
  discharge_or_death:
    expr: or(icu_discharge, death, hospital_discharge)

  # Plain predicates
  sodium:
    code: ???
  abnormally_low_sodium:
    code: ???
    value_min: null
    value_max: ???

trigger: icu_admission

windows:
  input:
    start: null
    end: trigger + 24h
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  # do not allow icu discharge to happen within the input + target window.
  no_discharge:
    start: trigger
    end: start + 48h
    start_inclusive: False
    end_inclusive: True
    has:
      icu_admission: (None, 0)
      discharge_or_death: (None, 0)
  target:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      sodium: (1, None)
    label: abnormally_low_sodium
